### ISSUE TITLE
Args/all.hpp, File missing error

### ISSUE THREAD

**Issue by shujaatak** [igormironchik/cfgfile#1]
On compiling Stock I get this error:
\stock\3rdparty\cfgfile\generator\main.cpp:42: error: Args/all.hpp: No such file or directory

I have download and extracted cfgfile to stock/cfgfile but still I am getting this error, I am on windows, can you please tell me possible solution?

**Edited:**
Never mind, I downloaded **args-parser** and extracted in Args folder and now this issue has been resolved.

**Comment by igormironchik** [comment]
git submodule update --init --recursive
